package com.arche.threply.ime.rime

/** 扩展词库第一部分：时间、数量、动词、形容词 */
internal object RimeFallbackLexiconExt1 {

    val entries: Map<String, List<String>> = mapOf(
        // 时间日期
        "nian" to listOf("年", "念"),
        "yue" to listOf("月", "约", "越"),
        "xingqi" to listOf("星期", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期天"),
        "xingqiyi" to listOf("星期一", "周一"),
        "xingqier" to listOf("星期二", "周二"),
        "xingqisan" to listOf("星期三", "周三"),
        "xingqisi" to listOf("星期四", "周四"),
        "xingqiwu" to listOf("星期五", "周五"),
        "xingqiliu" to listOf("星期六", "周六"),
        "xingqitian" to listOf("星期天", "周日"),
        "zhoumo" to listOf("周末", "周末好"),
        "shangwu" to listOf("上午"),
        "zhongwu" to listOf("中午"),
        "xiawu" to listOf("下午"),
        "wanshang" to listOf("晚上", "今晚"),
        "zaoshang" to listOf("早上", "早晨"),
        "zaochen" to listOf("早晨"),
        "banye" to listOf("半夜"),
        "lingchen" to listOf("凌晨"),
        "xiaoshi" to listOf("小时"),
        "fenzhong" to listOf("分钟"),
        "shijian" to listOf("时间", "时间到"),
        "riqi" to listOf("日期"),
        "houtian" to listOf("后天"),
        "qiantian" to listOf("前天"),
        "shanggeyue" to listOf("上个月"),
        "xiageyue" to listOf("下个月"),
        "jinnian" to listOf("今年"),
        "qunian" to listOf("去年"),
        "mingnian" to listOf("明年"),
        "jintian" to listOf("今天", "今天下午", "今天晚上"),
        "mingtian" to listOf("明天", "明天见", "明天再说"),
        "zuotian" to listOf("昨天", "昨天晚上"),
        "xianzai" to listOf("现在", "现在就", "现在可以"),
        "dengyixia" to listOf("等一下", "稍等一下", "等会儿"),
        "shaodeng" to listOf("稍等", "稍等一下"),
        "mashang" to listOf("马上", "马上来", "马上好"),
        "shenmeshihou" to listOf("什么时候", "啥时候"),
        "zenmeban" to listOf("怎么办", "怎么处理"),
        // 数量
        "ling" to listOf("零", "领", "灵"),
        "bai" to listOf("百", "白", "摆"),
        "duo" to listOf("多", "朵"),
        "shao" to listOf("少", "绍"),
        "duoshao" to listOf("多少", "多少钱"),
        "jige" to listOf("几个", "几"),
        "yixie" to listOf("一些", "有些"),
        "yidian" to listOf("一点", "一点点"),
        "yidiandian" to listOf("一点点"),
        "henduo" to listOf("很多", "好多"),
        "haoduo" to listOf("好多", "很多"),
        "suoyou" to listOf("所有", "所有的"),
        "quanbu" to listOf("全部", "全部的"),
        "dabufen" to listOf("大部分"),
        "xiaobufen" to listOf("小部分"),
        // 常用动词
        "zuoshenme" to listOf("做什么", "做啥"),
        "kanjian" to listOf("看见", "看到"),
        "kandao" to listOf("看到", "看见"),
        "tingshuo" to listOf("听说", "听说过"),
        "shuohua" to listOf("说话"),
        "xiezuo" to listOf("写作"),
        "dushu" to listOf("读书"),
        "xiang" to listOf("想", "向", "像", "象"),
        "xiangxiang" to listOf("想想", "想象"),
        "zhidao" to listOf("知道", "知道了"),
        "renshi" to listOf("认识", "认识你"),
        "lijie" to listOf("理解", "理解你"),
        "dong" to listOf("懂", "东", "冬"),
        "hui" to listOf("会", "回", "汇"),
        "neng" to listOf("能", "能够"),
        "nenggou" to listOf("能够"),
        "yao" to listOf("要", "药", "腰"),
        "xuyao" to listOf("需要", "需要你"),
        "bixu" to listOf("必须"),
        "gei" to listOf("给", "给你", "给我"),
        "geini" to listOf("给你", "给你的"),
        "geiwo" to listOf("给我", "给我看"),
        "song" to listOf("送", "松", "宋"),
        "mai" to listOf("买", "卖", "麦"),
        "goumai" to listOf("购买"),
        "yong" to listOf("用", "永", "勇"),
        "shiyong" to listOf("使用"),
        "dadianhua" to listOf("打电话"),
        "dianhua" to listOf("电话", "打电话"),
        "kaishi" to listOf("开始", "开始了"),
        "jieshu" to listOf("结束", "结束了"),
        "tingzhi" to listOf("停止"),
        "jixu" to listOf("继续", "继续吧"),
        "baochi" to listOf("保持"),
        "baozheng" to listOf("保证"),
        "baohu" to listOf("保护"),
        "baocun" to listOf("保存"),
        "shanchu" to listOf("删除"),
        "xiugai" to listOf("修改"),
        "tianjia" to listOf("添加"),
        "fuzhi" to listOf("复制"),
        "niantie" to listOf("粘贴"),
        "quxiao" to listOf("取消"),
        "tuichu" to listOf("退出"),
        "guanbi" to listOf("关闭"),
        "dakai" to listOf("打开"),
        "jinru" to listOf("进入"),
        "likai" to listOf("离开"),
        "fanhui" to listOf("返回"),
        "zoulu" to listOf("走路"),
        "paobu" to listOf("跑步"),
        "tiaowu" to listOf("跳舞"),
        "changge" to listOf("唱歌"),
        "youxi" to listOf("游戏", "玩游戏"),
        "wanyouxi" to listOf("玩游戏"),
        // 形容词
        "rongyi" to listOf("容易"),
        "kunnan" to listOf("困难"),
        "jiandan" to listOf("简单"),
        "fuza" to listOf("复杂"),
        "qingchu" to listOf("清楚"),
        "zhongyao" to listOf("重要"),
        "tebie" to listOf("特别"),
        "putong" to listOf("普通"),
        "pianyi" to listOf("便宜"),
        "mianfei" to listOf("免费"),
        "shoufei" to listOf("收费"),
        "anquan" to listOf("安全"),
        "weixian" to listOf("危险"),
        "ganjing" to listOf("干净"),
        "piaoliang" to listOf("漂亮"),
        "meili" to listOf("美丽"),
        "congming" to listOf("聪明"),
        "nuanhuo" to listOf("暖和"),
        "liangkuai" to listOf("凉快"),
        "shufu" to listOf("舒服"),
        "nanshou" to listOf("难受"),
        "lei" to listOf("累", "类", "泪"),
        "teng" to listOf("疼", "腾"),
        "shuang" to listOf("爽", "双")
    )
}
